# Generated by Django 3.0 on 2021-03-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=2000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1024)),
                ('subtitulo', models.CharField(max_length=1024)),
                ('contenido', models.TextField(max_length=10000)),
                ('imagen', models.ImageField(upload_to='publicaciones')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
